### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by eliizaveta** [Ilya-503/Autotest_OK#2]
### 1 

лучше увеличивать таймауты в местах, где необходимо
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/BaseTest.java#L14

### 2
все тесты начинаются с открытия страницы одноклассников, а страница логина может быть открыта и другими способами (например при выходе из учетной записи) поэтому лучше вынести переход на сайт по ссылке в BaseTest, а в конструкторе страницы логина оставить только метод проверки ключевых элементов для того, чтобы понять, загрузилась ли она
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/LoginPageTest.java#L22

### 3
аннотация @ Test потерялась
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/LoginPageTest.java#L25

### 4
добавлять сообщения в ассерты
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/LoginPageTest.java#L28

### 5
ожидаемые сообщения вынести в константы
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/LoginPageTest.java#L38

_просто предложение для экспериментов_
можно попробовать использовать вместо @ ValueSource - @MethodSource("provideInvalidParams")
где provideInvalidParams  что-то такое

```
private static Stream<Arguments> provideInvalidParams() {
        return Stream.of(
                Arguments.of(wrong_login, password, wrong_login_error),
                Arguments.of(null, password, enter_login_error),
                Arguments.of(login, null, enter_pwd_error)
        );
```
        
а тест привести к виду

```
@ParameterizedTest(name = "login: {0}, pwd: {1}, error : {2} ")
@MethodSource("provideInvalidParams")
    public void testEmptyPasswordField(String login, String pwd, String error) {
        loginPage
                .setLogin(login)
                .setPassword(pwd)
                .submit();
        assertEquals(error, loginPage.getErrorString(), "Ошибка не совпадает с ожидаемой");
    }
```

место в коде, о котором шла речь :)
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/LoginPageTest.java#L33

### 6
все названия диалогов и тд в константы
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/MessagePageTest.java#L24

### 7
уже есть в бейзтесте, от которого наследуемся, зачем в афтере теста еще раз?
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/MessagePageTest.java#L35

### 8
у 5го джаваюнита есть [assertArrayEquals](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertArrayEquals-short:A-short:A-java.lang.String-) кстати
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/MusicPageTest.java#L39

### 9
обычно в шаги выносят либо все либо ничего
как мне кажется нет смысла делать шаг логина
достаточно сделать функцию логина в пейдже
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/Step.java#L3

### 10
перед действиями с элементами проверять видимость SUBMIT_BTN.shouldBe(visible.because("Нет кнопки подтверждения")).click();
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/loginPage/LoginPage.java#L35

### 11
локаторы в константы
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/mainPage/MainPage.java#L18
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/messagePage/MessageWrapper.java#L32
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/messagePage/MessageWrapper.java#L36
и тд

### 12
зачем
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/messagePage/MessagePage.java#L46

### 13
лучше is(visible)
https://github.com/Ilya-503/Autotest_OK/blob/d6a42e8bba73a42008e769468d21a7a68a78de7e/src/test/java/pages/messagePage/MessagePage.java#L52

### 14
в методы validate() можно добавить больше проверок ключевых элементов

я в тамтам https://tt.me/riinj

**Comment by Ilya-503** [comment]
All points fixed
